add_newline = true

format = """
╭─$directory
╰─$character
"""
right_format = "$git_branch $git_status"
# palette = 'foo'

[directory]
format = '[\[$path]($style)\]'
style = "cyan"
truncation_length = 2
truncate_to_repo = true
truncation_symbol = "../"
home_symbol = '~'
read_only_style = 'red'

[git_branch]
format ='[\[$symbol$branch(:$remote_branch)]($style)\]'
symbol = " "

[character]
format ="$symbol "
success_symbol = ""
error_symbol = ""

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'